// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

import './App.css'
;

function App(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "AI Will Do It For You",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Our AI the pinnacle of Intelligence.\nIt replace what a human does -\nit reads, it watch movies, it listen to music."
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "What media do you want it to consume?",
                              className: "text-xl font-semibold"
                            }),
                        JsxRuntime.jsxs("form", {
                              children: [
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        "Choose a media you want the AI to comsume:",
                                        JsxRuntime.jsx("input", {
                                              className: "mt-2 p-2 border rounded",
                                              name: "uploaded_content",
                                              placeholder: "Enter a URL",
                                              type: "url",
                                              onKeyDown: (function ($$event) {
                                                  var match = $$event.key;
                                                  if (match !== "Enter") {
                                                    return ;
                                                  }
                                                  $$event.preventDefault();
                                                  console.log("URL submitted by Enter.");
                                                  setCount(function (count) {
                                                        return count + 1 | 0;
                                                      });
                                                })
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Upload",
                                      className: "mt-3 p-2 bg-blue-500 text-white rounded",
                                      type: "",
                                      onClick: (function (param) {
                                          setCount(function (count) {
                                                return count + 1 | 0;
                                              });
                                        })
                                    }),
                                "count is " + match[0].toString()
                              ]
                            })
                      ],
                      className: "mt-5"
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
