// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Functions from "./Functions.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

import './App.css'
;

function App(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setText = match$1[1];
  var text = match$1[0];
  var clicked = function (param) {
    console.log("Button clicked!");
    setCount(function (count) {
          return count + 1 | 0;
        });
    var match = Functions.classify(text);
    if (match.length !== 0) {
      console.log("Media types found for the URL.");
    } else {
      console.log("No media types found for the URL.");
    }
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "AI Will Do It For You",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Our AI the pinnacle of Intelligence.\nIt replace what a human does -\nit reads, it watch movies, it listen to music."
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h3", {
                              children: "What media do you want it to consume?",
                              className: "text-xl font-semibold"
                            }),
                        JsxRuntime.jsxs("form", {
                              children: [
                                JsxRuntime.jsxs("label", {
                                      children: [
                                        "Choose a media you want our AI to consume for you:",
                                        JsxRuntime.jsx("input", {
                                              className: "mt-2 p-2 border rounded",
                                              id: "uploaded_content",
                                              name: "uploaded_content",
                                              placeholder: "Enter a URL",
                                              type: "url",
                                              onKeyDown: (function ($$event) {
                                                  var match = $$event.key;
                                                  if (match !== "Enter") {
                                                    return ;
                                                  }
                                                  $$event.preventDefault();
                                                  console.log("URL submitted by Enter.");
                                                  clicked($$event.target.value);
                                                }),
                                              onChange: (function ($$event) {
                                                  setText($$event.target.value);
                                                })
                                            })
                                      ]
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Upload",
                                      className: "mt-3 p-2 bg-blue-500 text-white rounded",
                                      type: "",
                                      onClick: clicked
                                    }),
                                "count is " + match[0].toString()
                              ]
                            })
                      ],
                      className: "mt-5"
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
